name: MinetownsWhitelist
author: jessenic
main: net.minetowns.whitelist.WLPlugin
version: 1.1
depend: [Vault]
commands:
   rules:
      description: Rules command
      usage: /<command> (accept|reload)
      alias: wl whitelist white-list